image:
  widths: [600, 900, 1300]
  # shortcode_widths: [600, 900, 1300]
  # render_hook_widths: [600, 900, 1300]
  densities: [1, 2]
  formats: [original, webp]
  fit: cover
  class: img-fluid
  figure_class: figure
  figcaption_class: figure-caption
  figcaption_title_h: 4
  figure_image_class: "figure-img img-fluid"
  render_hook_wrapper_class: img-wrapper
  shortcode_wrapper_class: img-wrapper
  render_hook: false
  loading: lazy
  lqip_blur_amount: 6
  lqip_div_factor: 2
  gif_div_factor: 10
  provider: false
  suppress_width_warning: false
  type: page # or global
  min_width_difference: 40
  noscript: false


# developer notes
